### ISSUE TITLE
Parser error when have multi line comment after data table.

### ISSUE THREAD

**Issue by tuanvle** [cucumber/gherkin3#106]
```
Feature: Using calculator to calculate total addition, multiplication of list number

  This feature used to do addition and multiplication for all numbers in the list.
  In this test we just test for integer numbers.

  Background:
    Given I have list of number
      |12|
      |3 |
      |45|
      |2 |        

    # This scenario for addition operation

    """
    This feature used to do addition and multiplication for all numbers in the list.
    In this test we just test for integer numbers.
    """
  Scenario: Add all number in list
    When I add all number in list
    Then the result after adding all number in list should be 62

    # This scenario for multiplication operation
  Scenario: Multiply all number in list
    When I multiply all number in list
    Then the result after multiplying all number in list should be 3240

```

Throws exception when parse this feature with above content.

**Comment by aslakhellesoy** [comment]
Did you expect both the data table and the doc string to be passed as arguments to the background step?

**Comment by tuanvle** [comment]
@aslakhellesoy No, I did not. I just does not want to have an exception when parsing this feature.
Here is the exception.

```
gherkin.ParserException$CompositeParserException: Parser errors:
(13:5): expected: #EOF, #TableRow, #StepLine, #TagLine, #ScenarioLine, #ScenarioOutlineLine, #Comment, #Empty, got '"""'
(14:5): expected: #EOF, #TableRow, #StepLine, #TagLine, #ScenarioLine, #ScenarioOutlineLine, #Comment, #Empty, got 'This feature used to do addition and multiplication for all numbers in the list.'
(15:5): expected: #EOF, #TableRow, #StepLine, #TagLine, #ScenarioLine, #ScenarioOutlineLine, #Comment, #Empty, got 'In this test we just test for integer numbers.'
(16:5): expected: #EOF, #TableRow, #StepLine, #TagLine, #ScenarioLine, #ScenarioOutlineLine, #Comment, #Empty, got '"""'
	at gherkin.Parser.parse(Parser.java:148)
	at gherkin.Parser.parse(Parser.java:115)
	at gherkin.Parser.parse(Parser.java:111)
	at gherkin.Parser.parse(Parser.java:107)
```

**Comment by aslakhellesoy** [comment]
Why do you have a DocString underneath the table? It looks like you're using it like a comment?

**Comment by tuanvle** [comment]
Yup, it's just a comment.

**Comment by aslakhellesoy** [comment]
You can't use [DocStrings](https://cucumber.io/docs/reference#doc-strings) and comments. You have to use `#` for [comments](https://cucumber.io/docs/reference#comments).

**Comment by maisells** [comment]
Got this message too and I don't even know what DocStrings is.  I just use # for comments.  Why is Selenium complaining about a file that shouldn't even be called by the Cucumber script I am running?

**Comment by maisells** [comment]
<img width="1009" alt="screen shot 2016-08-25 at 1 12 17 pm" src="https://cloud.githubusercontent.com/assets/12070836/17988998/58b48506-6ae7-11e6-97d6-0fa6f6fe7bd4.png">

**Comment by aslakhellesoy** [comment]
@DougMaisells rather than commenting on a closed issue, please create a new one, and make sure you provide us with a Gherkin document that will allow us to reproduce the issue.

Please mark it up in the issue using triple backticks - like so:

<pre>
```gherkin
Feature: bla bla
```
</pre>

**Comment by DougMaisells** [comment]
Sorry, I did not see the issue was closed nor do I know your process tracking mechanism or process.  A co-worker sent me the issue to try and resolve my issue but as usual with internet help, when I read the response, the help is of no help.  I opened a new ticket.

Douglas.Maisells@granicus.com
[email-Sig_peak2]

**Comment by Skhoshhal** [comment]
is a solution worked for you ? I have the same problem can you help me ? thanks

**Comment by enkessler** [comment]
@Skhoshhal The solution is to mark comment lines with a `#`. This is the only valid way to identify a comment in Gherkin.
