### ISSUE TITLE
Objective C Parser not working

### ISSUE THREAD

**Issue by anwol004** [cucumber/gherkin3#117]
Hello I am trying to install the version but I get an error. Can anyone provide me with a little guide What do I need to make it work!

i try this: 

   GHParser *parser = [GHParser new];
   id parsingResult = [parser parse:filename];

but the log says:

2015-11-03 11:59:39.392 Gherki[10534:917811] -[GHParser parse:]: unrecognized selector sent to instance 0x60000002b340
2015-11-03 11:59:39.392 Gherki[10534:917811] *** Canceling drag because exception 'NSInvalidArgumentException' (reason '-[GHParser parse:]: unrecognized selector sent to instance 0x60000002b340') was raised during a dragging session

Greetz

**Comment by brasmusson** [comment]
@anwol004 I cannot give you any specific guidance with respect to the Objective C version. However, if you have not tried to use the version in https://github.com/cucumber/gherkin-objective-c, maybe you should. As we do not (yet) run the Objective-C version on [Travis CI](https://travis-ci.org/cucumber/gherkin3), it is possible that a problem can have sneaked in unnoticed in this repo (that is in this commit https://github.com/cucumber/gherkin3/commit/d2f31a6348c5b75dad3c2d0035d154c82948e37d)

**Comment by brasmusson** [comment]
It should be fixed by https://github.com/cucumber/gherkin3/commit/fc7af5ac121e08abf8685062e3e43658c6ad7f82 (says [Travis](https://travis-ci.org/cucumber/gherkin3/builds/89073689)).

**Comment by anwol004** [comment]
@brasmusson ok but this solution has nothing to do with my problem

**Comment by aslakhellesoy** [comment]
@LiohAu can you help?

**Comment by LiohAu** [comment]
This méthod (parse:) is defined in a category so maybe you're missing an "-all_load" linker flag ?

**Comment by anwol004** [comment]
ohh thank you @LiohAu you are right :-)
