### ISSUE TITLE
Implement a Gherkin parser in crystal programming languange

### ISSUE THREAD

**Issue by anilreddy** [cucumber/gherkin3#119]
I recently found that Crystal Programming language has similar syntax as ruby(approx 90%). It is a static type but with extreme performance. This is the home page: http://crystal-lang.org/

It is very fast see the benchmarks: http://www.stefanwille.com/2015/05/redis-clients-crystal-vs-ruby-vs-c-vs-go/

**Comment by aslakhellesoy** [comment]
I don't want an open ticket for every imaginable obscure language. Please send a pull request if you have implemented the parser for a particular language.
