### ISSUE TITLE
Separate repo for Objective-C parser

### ISSUE THREAD

**Issue by alexmx** [cucumber/gherkin3#120]
Hello, from your `Contributing.md` file:
> Gherkin3 is implemented in several different languages, and each language implementation lives in a separate git repository.

Is that right? Can I find it in a separate repo? As I need it for one personal project. I'm thinking about how to integrate it as 3rd party without getting the entire **gherkin3** repo.

Also is the current implementation ready to be used in real projects, or it is a work in progress?

Thank you.

**Comment by brasmusson** [comment]
The separate git repo for the Objective-C version is [cucumber/gherkin-objective-c](https://github.com/cucumber/gherkin-objective-c).
