### ISSUE TITLE
Fix ruby build

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/gherkin3#127]
Looking at [this build](https://travis-ci.org/cucumber/gherkin-ruby/builds/90416555) it looks like something (simplecov?) depends on some junk called tins that only runs on ruby 2.0.

Let's just remove simplecov then.

**Comment by Zearin** [comment]
:+1:

**Comment by Zearin** [comment]
I’m not sure `simpleconv` is the culprit.  Looks like it’s the `tins` gem whose installation goes awry.

**Comment by aslakhellesoy** [comment]
tins is a transitive dependency of something else. Log suggests it's simplecov.

**Comment by Zearin** [comment]
Ah okay.  I have much to learn about gems. :)

**Comment by Zearin** [comment]
Okay.  I learned a teeny bit:

```
$ gem dep tins --reverse
Gem tins-1.6.0
  gem_hadar (~> 1.2.0, development)
  test-unit (~> 2.5, development)
  Used by
    coveralls-0.8.6 (tins (= 1.6.0))
    term-ansicolor-1.3.0 (tins (~> 1.0))
```
