### ISSUE TITLE
Separate git repo for each language?

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/gherkin3#13]
Node.js' [npm](https://www.npmjs.com/) and PHP's [Composer](https://getcomposer.org/) require packages/modules to be defined in the root of a repo. -At least if they are to be consumed as git repos. See #4 and #9 for more details.

My only reservation about splitting this repo into several repos (gherkin-csharp, gherkin-golang etc) is that it might make it more difficult to keep the implementations in sync. But maybe not.

All the language-specific repos would be "linked" to this repo using git submodule (or something similar), and maybe it wouldn't be that much of an issue.

WDYT?

**Comment by everzet** [comment]
How about subtree splits: https://help.github.com/articles/splitting-a-subfolder-out-into-a-new-repository/ ?

**Comment by muhqu** [comment]
I like the subtree split idea. it shouldn't be pain when you think of the subtree split repository as some kind of release artifact. Like you would package software for download, you would push squashed changes to the split tree repository...

I just added a sample `push-release` target to the [golang/Makefile](https://github.com/cucumber/gherkin3/blob/master/golang/Makefile#L71-L72)... I temporarily pushed the changes to https://github.com/muhqu/go-gherkin3 ...

**Comment by mattwynne** [comment]
A thousand times yes. This will help keep things sustainable as we add more languages.

If we keep a master repo that includes all the language implementations as submodules, that will make it easier for people who hack on multiple language versions, and we can also have one travis build for that repo to show that everything's working across languages. Maybe a bit like https://github.com/rspec/rspec-dev?

Seems to me the submodule repo names shout be `gherkin3-go` `gherkin3-ruby` etc to keep them sitting next to each other.

**Comment by muhqu** [comment]
Fine with me, too.

>

**Comment by aslakhellesoy** [comment]
Cool. Let's name them `gherkin-ruby`, `gherkin-go` etc, without the 3 in the name.

**Comment by chmontgomery** [comment]
:+1:

**Comment by aslakhellesoy** [comment]
Ok folks, I have split the subfolders into separate repositories:

* github.com/cucumber/gherkin-csharp
* github.com/cucumber/gherkin-go
* github.com/cucumber/gherkin-java
* github.com/cucumber/gherkin-javascript
* github.com/cucumber/gherkin-ruby

I'm working on git subtrees next, and updating the build scripts.

**Comment by aslakhellesoy** [comment]
Allright - it's all reorganised now. See [CONTRIBUTING.md](https://github.com/cucumber/gherkin3/blob/master/CONTRIBUTING.md) - the beginning of the file describes how this new subtree stuff works.

@muhqu your `push-release` target seems redundant now that there is `add-remotes` and `push-subtrees` targets in the root `Makefile`.

**Comment by aslakhellesoy** [comment]
Allright - this is now done. It doesn't change much to the workflow. Keep working in this repo and do the occasional `make push-subtrees`.
