### ISSUE TITLE
allow tagging individual outline examples

### ISSUE THREAD

**Issue by akostadinov** [cucumber/gherkin3#142]
Hello,

would be useful to allow tagging individual outline examples and outline example tables. That would allow for easy ,mapping between scenarios/outlines and external test case management systems. For example to run test case management test case xyz, one can tag one or more examples of scenarios with @xyz tag. Exact convention up to user, this is illustrative.

**Comment by aslakhellesoy** [comment]
You can tag individual `Examples` and you can have as many of those as you want. We're not going to make individual rows taggable, it would be at odds with visual excel-like table editors.

**Comment by akostadinov** [comment]
Didn't know one can tag individual examples tables, thank you. Still I don't see why an editor can't adapt to row tagging.

But current functionality would work albeit one would need 4 lines instead 1.

**Comment by aslakhellesoy** [comment]
An Excel-like grid component wouldn't work well if there were tags between table rows.

**Comment by akostadinov** [comment]
well, if users don't like how it looks, then they could not use that feature. But I seriously doubt anybody willing to have tags on individual examples will prefer 10 tables with tags compared to 10 rows with tags regardless the editor in use. As it is all opt-in, I don't see why ignore this use case.

**Comment by aslakhellesoy** [comment]
Thanks for your insight. We won't be adding support for tags in individual rows.

**Comment by aslakhellesoy** [comment]
And it's not opt-in as you suggest. A standard grid component wouldn't be able to render it. It's important that the (whole) syntax can be easily supported by tools.

I also think your use case is rather unusual.

**Comment by akostadinov** [comment]
As I said current functionality works although a little more uglier than desired. So not pushing you to implement. Also it's OSS so nobody has the right to push anybody about anything. So I was going to not reply but since I see arguments over there, I can't resist replying as I can't actually agree with them.

I don't agree that syntax should be limited just for the convenience of tools when that prevents legitimate helpful functionality (moreover tools that only a subset of users would use).
wrt unusual use case - I guess that only small percentage of users do have an external test case management system but if one has really a lot of test cases and a medium/big team, not using an external test case management system is hindering efficiency. So for cucumber to integrate with that there must be some mapping between the two. At the moment we use inside the external system file:scenario name + arguments when outline is involved. But this is not very convenient as you can imagine. It's easier to map using tags that for example represent the external system test case id (associating from cucumber -> external system) instead of pointing from external system -> cucumber. That's because also it is desirable to be able to run cucumber standalone outside the external system.
I'm thinking that there is some (significant?) number of teams that start small but grow with time and can benefit from such functionality.

Here's an example difference between the two approaches:
```
  @example_outline
  Scenario Outline: I want an example outline
    ...

    Examples:
      | garga|marga |
      @case1
      |hodi | brodi |
      @case2
      |mura |    ura|
      @case3
      |foo|bar|
      @case4
      |fff|ggg|
      @case5
      |hhh|iii|
```
vs
```
  @example_outline
  Scenario Outline: I want an example outline
    ...
    @case1
    Examples:
      | garga|marga |
      |hodi | brodi |

    @case2
    Examples:
      | garga|marga |
      |mura |    ura|

    @case3
    Examples:
      | garga|marga |
      |foo|bar|

    @case4
    Examples:
      | garga|marga |
      |fff|ggg|

    @case5
    Examples:
      | garga|marga |
      |hhh|iii|
```

Pls tell me one thing. Did you just say that cucumber team will not implement this feature or that such feature will not be included regardless of it being implemented by external contributors? Just asking to know whether it's worth giving it a try if I find some free time..

**Comment by mattwynne** [comment]
@akostadinov would it not be more helpful to have a unique test case identifier for an Gherkin scenario or scenario outline example? You could be using `file:line` references from the test-case management tool -> Gherkin but that would be fairly brittle to changes in the Gherkin. We've done some experiments with a more stable ID system for test-cases [before](https://github.com/cucumber/gherkin/blob/master/features/json_formatter.feature#L168) and maybe that would be better for your use case?

Out of interest, which test case management tool are you using?

**Comment by akostadinov** [comment]
@mattwynne, as you  say `file:line` can't work, we use `file:name` and when only particular examples row is desired we also add the arguments (key->value pairs).
I looked at the test case above. It seems to me that in fact our current solution is similarly based on scenario name and arguments (when desired) but we use complete name instead of id. And I think using complete name is better for one can copy/paste it while ID not so easily. Also when arguments are involved, id is still based on line number which still requires getting to the exact arguments.

I find tags better because:
* you can select as many scenarios and examples as desired
* that can happen without complicated script logic or human effort (below more explanation)
* changing scenario/outline/table name and row numbers/content does not require altering the test case management system

wrt your question, we're using https://fedoraproject.org/wiki/Nitrate but is likely that we change it at some point.

What we do is setup a test run in Nitrate that contains all test cases we desire for the test iteration. Then read file:name + args data in json format from individual test cases. Then I have a simple test case manager filter to delegate to an implementation [1] that interacts with the actual test case management system (nitrate). 
Now nitrate implementation is complicated because of given a cucumber test case, it has to decide if scenario exist, is it an outline or a simple scenario, or is it only a row. Then wait to collect all scenarios described in the JSON and pass them down when asked with `tc_manager.next`.
Using id will not make things less complicated as far as I see.
Using tags on the other hand would allow the actual test case manager to receive all scenarios/test cases from the filter. Collect all of them with particular tag and then based on their result update the test case management system. This is a lot simpler than trying to understand what kind of test cases are these and perform complicated operations like row matching.

btw things need to be done strictly because we also use parallelism. So we run multiple cucumber processes. The test case manager object should grab exactly one test case that is not already processed by another runner, execute it and report result. We can't just lazily match cucumber test cases and report at cucumber exit.

Sorry, explaining code is hopeless. I hope I answered your question somehow.

[1] mostly the filter looks like this:
```
  TestCaseManagerFilter = Cucumber::Core::Filter.new(:tc_manager) do
    # called upon new scenario
    def test_case(test_case)
      tc_manager.push(test_case)

      # run each test case that manager returns; it means ready to be executed
      while case_to_run = tc_manager.next # yes, assignment
        tc_manager.signal(:start_case, case_to_run)
        case_to_run.describe_to receiver
        tc_manager.signal(:end_case, case_to_run)
      end
      return self
...
```

**Comment by mattwynne** [comment]
OK so it sounds to me like you're a user who has a genuine need, and has thought this through. I'd like to support you, provided we can add this feature without too much extra weight in the code.

Can I suggest the syntax is to put the tags after the last table pipe? It seems that will read better.

e.g.

```gherkin
  Scenario Outline:
    Given value <a>
    When action <b>
    Then outcome <c>

    Examples:
    | a | b | c |
    | 1 | 2 | 3 | @numeric
    | x | y | z | @letters @better
```

How does that look?

**Comment by aslakhellesoy** [comment]
That could work, but it would be a considerable amount of work to implement in the 7 languages we support now.

I'm not sure who'll volunteer for that.

**Comment by akostadinov** [comment]
@mattwynne , I can only say creative thinking. Nice way to have both sides happy.

**Comment by mattwynne** [comment]
Are you interested in helping @akostadinov? We can support you in learning how to contribute to Gherkin 3.

**Comment by akostadinov** [comment]
@mattwynne, I can look at the ruby version when I get some time.

**Comment by brasmusson** [comment]
Would this change the gherkin language definition ([gherkin.berp](https://github.com/cucumber/gherkin/blob/master/gherkin.berp#L23))? So that `Examples!` is defined:
```
Examples! := #ExamplesLine Examples_Description #TableRow #TableRowWithTags+
```
Tags should neither be allowed on rows in data tables nor on the header row of examples tables.

**Comment by mattwynne** [comment]
Nice one @brasmusson, thanks for helping get this started!

**Comment by akostadinov** [comment]
@brasmusson, thank you for giving me a starting point. I think that we should keep original 
```
Examples! := #ExamplesLine Examples_Description Examples_Table?
```
Because the other table type is `DataTable` so there should be no confusion between the two table types.

Then we can change `Examples_Table` definition as you suggested to:
```
Examples_Table! := #TableRow #TableRowWithTags*
```

What do you think about that?

I don't know if this is possible with `berp`. But something like this would look even better to me:
```
Examples_Table! := #TableRow TableRowWithTags*
TableRowWithTags! := #TableRow #TagLine?
```
If you can advise whether such approach is possible, that would be great. It seems to me it is not actually doable like that after looking into `lib/gherkin/token_matcher.rb` and `lib/gherkin/ast_builder.rb`.

Assuming the approach `#TableRowWithTags` is used, do you see any other places than the above two files to need adjustments? I'll have to dig through things anyway, but if you know off the top of your head, that can help. Thanks again!

**Comment by volkyeth** [comment]
This would be such a helpful feature for suites management. I can see it used to separate a @smoke test suite from a @regression one, for instance.

Is this still happening?

**Comment by aslakhellesoy** [comment]
@bwowk see my [comment above](https://github.com/cucumber/gherkin/issues/142#issuecomment-172575159) from Jan 18 2016

**Comment by volkyeth** [comment]
@aslakhellesoy I can volunteer for the implementation on https://github.com/Behat/Gherkin :grimacing:

**Comment by enkessler** [comment]
@aslakhellesoy  I'm interested in and could certainly use this change (see the second half of this comment). However, my first thought in reading the various comments in this and some of the linked threads is that this will get misused/abused.

If test cases are meaningfully different, then why isn't that reason for being different called out (i.e put them in a separate `Examples` table). If they are not meaningfully different, then isn't the user just doing exhaustive unit style testing at the more resource expensive functional level?

@bwowk Your use case of marking `@smoke` and `@regression` tests could be an example of such misuse. Why is row X the one that will get run for smoke testing but not row Y? 

---

@akostadinov Tracking individual test cases is pretty much what I would use this functionality for as well.

Up until now, I've used a [tool](https://github.com/enkessler/cuke_cataloger) to mark tests with identifiers. It's independent of any given management system but is often used in conjunction with one.

I turn something like this
````
Feature:

  Scenario:
    * a step

  Scenario Outline:
    * a step
  Examples: with rows
    | param 1 |
    | value 1 |
    | value 2 |
  Examples: without rows
    | param 1 |
````

into something like this
````
Feature:

  @test_case_1
  Scenario:
    * a step
  
  @test_case_2
  Scenario Outline:
    * a step
  Examples: with rows
    | param 1 | test_case_id |
    | value 1 | 2-1          |
    | value 2 | 2-2          |
  Examples: without rows
    | param 1 | test_case_id |
````

but being able to do this instead
````
Feature:

  @test_case_1
  Scenario:
    * a step
  
  Scenario Outline:
    * a step
  Examples: with rows
    | param 1 |
    | value 1 |  @test_case_2
    | value 2 |  @test_case_3
  Examples: without rows
    | param 1 |
````

might make things a little more understandable. Also, I wouldn't have to use a 'fake' column.

**Comment by aslakhellesoy** [comment]
@bwowk you mean after someone else has implemented it in the official parser? Ok.
