### ISSUE TITLE
Scenarios with Double quotes in the title do not run correctly

### ISSUE THREAD

**Issue by colej12** [cucumber/gherkin3#144]
When I have a word quoted in my Scenario name, a "Empty test suite" error is thrown by cucumber.

> Scenario: I have "quoted" text in my scenario title
> Given I have a scenario title
> When there are double quotes surrounding a word in my title
> Then I see an error "Empty test suite" in my output log

When multiple words are quoted, a "No such file or directory - <second word>" error is thrown instead.

> Scenario: Scenarios with "many quoted words" throws a completely different error
> Given I have a scenario title
> When there are double quotes surrounding multiple words in my title
> Then I see an error "No such file or directory - quoted. You can use `cucumber --init` to get started." in my output log.

**Comment by aslakhellesoy** [comment]
Please provide a stacktrace as well as what versions of cucumber and gherkin you have.

**Comment by aslakhellesoy** [comment]
Also please provide a Gherkin document that will let us reproduce the error.

Gherkin doesn't open files, so the "No such file or directory" error is not from Gherkin. Please open a separate ticket about that in the cucumber-ruby project.

**Comment by colej12** [comment]
No stack trace was generated for either of these errors.


Testing started at 2:17 PM ...
See http://www.oracle.com/technetwork/database/enterprise-edition/jdbc-faq-090281.html#01_03 for supported versions

0 scenarios
0 steps
0m0.001s

Process finished with exit code 0
Empty test suite.

-------
Testing started at 3:16 PM ...
See http://www.oracle.com/technetwork/database/enterprise-edition/jdbc-faq-090281.html#01_03 for supported versions

No such file or directory - Loan. You can use `cucumber --init` to get started.

Process finished with exit code 2
Empty test suite.

>gem 'activerecord', '4.1.4'
>gem 'activerecord-oracle_enhanced-adapter', '1.5.5'
>gem 'cucumber', '2.1.0'
>gem 'ffi', '1.9.9'
>gem 'jruby-openssl', '0.9.12'
>gem 'gherkin3', '3.1.2'
>gem 'jruby-win32ole'
>gem 'page-object', '0.9.6'
>gem 'pdf-reader', '1.3.3'
>gem 'rspec', '2.14.1'
>gem 'ruby-ole', '1.2.11.7'
>gem 'rubyzip', '1.1.0'
>gem 'selenium-webdriver', '2.47.1'
>gem 'spreadsheet'
>gem 'savon', '2.3.3'

I will also contact cucumber-ruby about the file missing issue.  Also, do you need me to provide step definitions and a directory structure to run the scenarios described above?

**Comment by aslakhellesoy** [comment]
Thanks for the versions. Now, please provide a minimal, but complete gherkin document that will reproduce this behaviour.

**Comment by colej12** [comment]
Running the scenarios at the feature level has made be start to think that this is related to Rubymine seven, rather than Gherkin.  However, I have attached the feature file that I used in my testing to this message, if you would like to look into it further.
[quotes_error.feature.txt](https://github.com/cucumber/gherkin3/files/69021/quotes_error.feature.txt)

**Comment by aslakhellesoy** [comment]
The attached document parses just fine with Gherkin, so this is probably a bug in some other tool you're using (maybe rubymine)
