### ISSUE TITLE
split repositories access

### ISSUE THREAD

**Issue by muhqu** [cucumber/gherkin3#15]
Hi @aslakhellesoy,

I've just pushed a few changes to master (f15cd9e4bade05602a3fa515e12886ae5ee5dfea...d552bc93333bdfa21ec605a370e7790308c8148f). I then tried to push these changes to the https://github.com/cucumber/gherkin-go split repository, but I don't have access to this yet:
> ERROR: Permission to cucumber/gherkin-go.git denied to muhqu.
> fatal: Could not read from remote repository.

Would you mind giving me push access the split repositories as well?

**Comment by aslakhellesoy** [comment]
Sorry about that @muhqu. Done!
