### ISSUE TITLE
Step.Argument and null object pattern, Node base class

### ISSUE THREAD

**Issue by gasparnagy** [cucumber/gherkin3#16]
Once we mentioned that we want to use a kind of null object pattern for Step.Argument, ie have something like an EmptyStepArgument instance for those steps that neither has a DataTable nor a DocString argument. The current C# version is implemented like this, but the others not. 

I would like to consolidate the implementations. Shall I remove the `EmptyStepArgument`?

This is somewhat related to the `Node` base class, that has only a `Location`. As the EmptyStepArgument does not have a location, it cannot be a proper Node. 

In general: is the Node base class is part of the AST definition (ie has meaning) or just an implementation helper? In C# i did not need the base class as implementation helper, but I would introduce it if we see this as part of the AST.

**Comment by mattwynne** [comment]
We also use null object in cucumber-ruby-core - EmptyMultilineArgument.

We use a #match_locations? method in our AST currently, which gets around the problem of it not having a location.

I’d say that having a base class is an implementation detail, isn’t it? Isn’t the common interface more important to define?

**Comment by aslakhellesoy** [comment]
I see why it would be handy to have a null-object for this, but it creates a problem for the JSON representation of the AST. If we add it, steps with no DocString or DataTable will have an empty object here (as apposed to nothing), and that doesn't make much sense. We can't have a Location for nothing.

So I think we should leave it out in Gherkin. It can still exist in Cucumber/SpecFlow, but that's a different bounded context (and different classes).

I think it's really important to not let Cucumber have any knowledge of the Gherkin AST - except perhaps for pretty printing.

**Comment by gasparnagy** [comment]
OK. I remove the `EmptyStepArgument` it from .net

**Comment by gasparnagy** [comment]
done

**Comment by mattwynne** [comment]
I don’t get that - why can’t you have both - a value object to represent nothing *and* no node in the JSON representation? Why are they mutually exclusive?

**Comment by aslakhellesoy** [comment]
because the JSON generation (for Java at least) is done via reflection. If the `argument` field is null we end up with no `argument` property in the JSON (which is what we want), but if it has a value, we do. And it it's a null-object (presumably with no properties), it will be `{"argument": {}}` which is silly/ugly.

**Comment by mattwynne** [comment]
Well maybe reflection is not the right way to render the JSON then? I don’t like presentation concerns leaking into the object modelling.

**Comment by aslakhellesoy** [comment]
I agree in principle, but sometimes pragmatism wins. If you feel strongly about it you know what to do @mattwynne.

**Comment by mattwynne** [comment]
Well I’d like to see how this pans out on the Ruby codebase first, then I’ll apply my opinions into the Java code :)
