### ISSUE TITLE
Rename gherkin-csharp to gherkin-dotnet

### ISSUE THREAD

**Issue by gasparnagy** [cucumber/gherkin3#17]
I think gherkin-dotnet would be a more proper name...

**Comment by aslakhellesoy** [comment]
I renamed the subtree repo to https://github.com/cucumber/gherkin-dotnet, but now the subtree push failed, so I had to recreate that repo. All history is lost in https://github.com/cucumber/gherkin-dotnet, but it's intact in this repo.
