### ISSUE TITLE
Step.Text vs Name

### ISSUE THREAD

**Issue by gasparnagy** [cucumber/gherkin3#18]
I tried to make a research on what we discussed so far.

In the original discussion we agreed on `text` (against `body` and `name`):
https://groups.google.com/d/msg/cukes-devs/RCnkmXsLQEs/J4K8mPxzOw0J

There was also a discussion as part of the cucumber-core, where it went more for the `name`
https://groups.google.com/forum/#!searchin/cukes-devs/Title/cukes-devs/YAdxutcTlYA/rPREkIzahYUJ

The C# implementation uses `text` the others `name`. What should it be then?

/CC @aslakhellesoy @tooky @mattwynne

**Comment by muhqu** [comment]
:+1: for `text`

**Comment by aslakhellesoy** [comment]
Yes, let's go for `text`. It's not the *name* of the step - it's the *text* of the step.

I can do the refactoring for ruby, java, javascript, go. @gasparnagy can you finish it off for csharp when I'm done? I'll give you a heads up in this ticket.

**Comment by gasparnagy** [comment]
Yes/fine!

**Comment by aslakhellesoy** [comment]
Actually - I'll do C# too. Easy.

**Comment by aslakhellesoy** [comment]
Oh - it's already done I see...

**Comment by aslakhellesoy** [comment]
Fixed in ac1854b84c00e49ac23815ac9e234d590276bd56
