### ISSUE TITLE
enable sourcegraph

### ISSUE THREAD

**Issue by muhqu** [cucumber/gherkin3#25]
We should consider enabling [sourcegraph](https://sourcegraph.com/) for the language specific repositories... AFAIK it is free of charge for open-source projects.
* https://sourcegraph.com/github.com/cucumber/gherkin-go
* https://sourcegraph.com/github.com/cucumber/gherkin-java
* https://sourcegraph.com/github.com/cucumber/gherkin-javascript
* https://sourcegraph.com/github.com/cucumber/gherkin-ruby

**Comment by muhqu** [comment]
btw, godoc.org already picked up the gherkin-go repository... see: https://godoc.org/github.com/cucumber/gherkin-go

**Comment by aslakhellesoy** [comment]
What would we be able to do (better) that we can't currently do?

**Comment by muhqu** [comment]
sourcegraph is a great tool that helps…
 - to identify who and what depends on your code and
 - what the implications of pull request might be... 
 - users of your lib/package to find usage examples (e.g. other peoples code that uses your code)

…also it is a great go-centric startup I like to push fwd! ;-) /cc @sqs

**Comment by aslakhellesoy** [comment]
Sure thing - go ahead and enable it. As long as I don't have to actively use it for code reviews and such - I'm using too many tools already ;-)

**Comment by muhqu** [comment]
@aslakhellesoy I would have done that if I would be allowed to do this... looks like this has to be done by the 'owner' of a repository... I'm just a 'collaborator'.

**Comment by aslakhellesoy** [comment]
Try again? I made you an owner.
