### ISSUE TITLE
Please add an explanation about how the acceptance suite works

### ISSUE THREAD

**Issue by stof** [cucumber/gherkin3#3]
I'm one of the maintainers of the [Behat](https://github.com/Behat) project, which is considered as the official PHP implementation of Cucumber. We have our own Gherkin parser implementation written in PHP for that.
I think it would be great if we could run the Gherkin acceptance testsuite with our own parser to ensure consistency. Could you describe how the acceptance suite works so that we can try to achieve such setup ?

**Comment by aslakhellesoy** [comment]
I've written up some docs [here](https://github.com/cucumber/gherkin3/blob/master/CONTRIBUTING.md#implementing-a-parser-for-a-new-language). I hope that clears it up.

See the input and output files here: https://github.com/cucumber/gherkin3/tree/master/testdata/good (the `.ast` files will go away soon - ref [TODO](https://github.com/cucumber/gherkin3/blob/master/TODO.md).

Feel free to reopen if anything is not clear.

**Comment by stof** [comment]
There is 1 thing which would be needed though: describing the format in which the AST is expected to be dumped (even though this can probably be guessed by looking at the json file).

Btw, does a new language new to implement the dumping to .ast files to be able to pass the testsuite or is the json dumping enough ?

**Comment by aslakhellesoy** [comment]
I suppose we could specify the AST structure using JSON schema or something. TBH i think a simple UML class diagram would suffice. I can make one and sdd it to the README.

The `.ast` files and the pretty printer will go away (se TODO.md - the .NET impl is a little behind). The `.ast.json` dumping is enough.
