### ISSUE TITLE
Examples of special characters

### ISSUE THREAD

**Issue by chmontgomery** [cucumber/gherkin3#39]
Is there documentation on what special characters are allowed in the `examples` table? E.g. `-`, `?`, `'`, etc? When using the [ace editor](http://ace.c9.io/build/kitchen-sink.html) syntax highlighting, using those characters seem to break the highlighting.

![gherkin-special-characters](https://cloud.githubusercontent.com/assets/232356/7821318/8e9af764-03b3-11e5-94e4-b654bfce8562.png)

I understand that's not your problem, but curious what syntax is allowed.

**Comment by aslakhellesoy** [comment]
You can use any character you want in table cells, so this sounds like an Ace bug. Gherkin2 lets you use a `|` character if you escape it with a backslash: `\|`. Gherkin3 doesn't support that yet, so I created #40.
