### ISSUE TITLE
[JavaScript] NPM Package 3.0.0

### ISSUE THREAD

**Issue by danielpacak** [cucumber/gherkin3#43]
As far as I understood, the JavaScript implementation in this repository is supposed to replace [this](https://github.com/cucumber/gherkin/blob/master/js/package.json) NPM package, which is already released (version 2.12.2) and accessible from [here](https://www.npmjs.com/package/gherkin).

Now I'm wondering:

1. Is this implementation production ready? (cucumber-js is still using this old no-longer-supported JS parser)
2. When do you plan release of Gherkin NPM package 3.0.0?
3. Where can I find it's public API documentation?

Looking at src code (especially test suite) it seems that some bits are missing to make it even a release candidate. Anyway, it would be nice to have a reliable status of this library in README.md so we can push release forward.

**Comment by aslakhellesoy** [comment]
1. It's fairly stable and feature complete, but some minor parts of the API might change before we cut the first release
2. Hopefully before Sept 2015, but no promises made
3. There is no documentation beyond what's in the README.

Can you be more expicit about what you think is missing?
What are you planning to use the library for? What are you making?

**Comment by danielpacak** [comment]
Sorry, I made my judgement based on the numer of unit tests run and reported [here](https://travis-ci.org/cucumber/gherkin-javascript). Not sayin' that something is missing or does not work though.

I'm working on [FeatureBook](https://github.com/SOFTWARE-CLINIC/featurebook) which is a specification editor/browser for non technical folks.

Another project I'm interested in is [ez-bdd](https://github.com/waxxfetish/ez-bdd). Essentially, this one is a command line tool that transforms a Gherkin source file into a Jasmine spec scaffold.

In both cases we need a reliable Gherkin parser accessible from NPM repo.

**Comment by aslakhellesoy** [comment]
3.0.0 is released to NPM!

**Comment by danielpacak** [comment]
Great! Thank you :dancers:
