### ISSUE TITLE
Multilpe line examples, annotated examples and column separator alternative

### ISSUE THREAD

**Issue by thr0w** [cucumber/gherkin3#51]
Hi, I suggest new features for Gherkin language specification:

## Multilne in example tables
It's very useful and simple to parse, just use a blank or a dashed line as separator. [Like that] (https://github.com/thr0w/yadda/blob/master/test/features/multiline_example_scenarios.feature).
> Identation it's important in multiline mode. 

## Annotations for each example
 [Like that] (https://github.com/thr0w/yadda/blob/master/test/features/example_scenarios_with_annotations.feature) 

## And allow use | (\u007C) or ┆ (\u2506) as column separator. 

Note: I've tried to make a fork with these changes but I can't understand how gherkin.berp define @TableRow. 

Thanks.
Best reggards.

**Comment by aslakhellesoy** [comment]
Please create a separate ticket for each proposed change so they can be discussed and possibly closed independently.
