### ISSUE TITLE
Where gherkin.berp defines @TableRow?

### ISSUE THREAD

**Issue by thr0w** [cucumber/gherkin3#55]
I've tried to make changes for apply request pulls for issues #52 , #53  and #54 but i'm newer with `berp`.

I can imagine that @TableRow reffers to how parse each example but I where it's defined?

Thanks

**Comment by aslakhellesoy** [comment]
Gherkin3 consists of a hand-written lexer and a parser generated by Berp.

TableRow is matched in [TokenMatcher](https://github.com/cucumber/gherkin3/blob/master/ruby/lib/gherkin3/token_matcher.rb#L42), which is part of the lexer. (Similarly in Go, Java, JavaScript, C#).
