### ISSUE TITLE
Document how to release to NuGet

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/gherkin3#58]
I think we need a `gherkin.nuspec`. We also need a "Making a release" section in `dotnet/CONTRIBUTING.md` - similar to https://github.com/cucumber/gherkin3/blob/master/ruby/CONTRIBUTING.md#make-a-release

Can you add this @gasparnagy ?

**Comment by dirkrombauts** [comment]
I'm chiming in because @aslakhellesoy suggested I help with this issue in order to speed up the .NET release of Gherkin3.

There already is a gherkin.nuspec - it's in $\dotnet\Gherkin.NuGetPackages\Gherkin\Gherkin.nuspec

**Comment by gasparnagy** [comment]
@dirkrombauts yes... i created that, but it did not seem to work on the CI. I'm available next week from Tue, maybe we can have a chat or do something together.

**Comment by dirkrombauts** [comment]
Let's do that ...

**Comment by dirkrombauts** [comment]
@gasparnagy I'm available today from (roughly) 10:30 onwards. When would suit you? My skype username is dirk.rombauts btw ...

**Comment by gasparnagy** [comment]
Almost the same for me. I ping you on Skype.

**Comment by gasparnagy** [comment]
@dirkrombauts i think i connected to a wrong skype account... now i tried with the other one too.

**Comment by dirkrombauts** [comment]
Is there anything more to be done for this issue?

**Comment by aslakhellesoy** [comment]
I think we're good - thanks a lot for all your help @dirkrombauts!

Before I make a new release I'd like to see #65 completed. If you want to help you could send a PR for .NET similar to 3fe0cea3f1ca9cb78cc81afcb3c279b2d0fcd648 and d724a0947895f79307841daeaa215c88ec703b20
