### ISSUE TITLE
Python: Cannot parse multiple times

### ISSUE THREAD

**Issue by araines** [cucumber/gherkin3#62]
```python
from gherkin3.token_scanner import TokenScanner
from gherkin3.parser import Parser

parser = Parser()
print parser.parse(TokenScanner("Feature: 1"))
print parser.parse(TokenScanner("Feature: 2"))
```

Results in:

```python
{'language': 'en', 'keyword': u'Feature', 'tags': [], 'comments': [], 'location': {'column': 1, 'line': 1}, 'scenarioDefinitions': [], 'type': 'Feature', 'name': u'1'}
{'language': 'en', 'keyword': u'Feature', 'tags': [], 'comments': [], 'location': {'column': 1, 'line': 1}, 'scenarioDefinitions': [], 'type': 'Feature', 'name': u'1'}
```

Note the name hasn't changed from 1 to 2.  Am I missing something in how this is supposed to be used?

**Comment by brasmusson** [comment]
This does not work either:
```
from gherkin3.token_scanner import TokenScanner
from gherkin3.ast_builder import AstBuilder
from gherkin3.parser import Parser

parser = Parser()
builder = AstBuilder()
print parser.parse(TokenScanner("Feature: 1"), builder)
print parser.parse(TokenScanner("Feature: 2"), builder)
```
But this does work:
```
from gherkin3.token_scanner import TokenScanner
from gherkin3.ast_builder import AstBuilder
from gherkin3.parser import Parser

parser = Parser()
builder = AstBuilder()
print parser.parse(TokenScanner("Feature: 1"), builder)
builder = AstBuilder()
print parser.parse(TokenScanner("Feature: 2"), builder)
```
So the current behaviour is that the same `AstBuilder` instance cannot be used in multiple calls to `parse` (or relying on the builder arguments default declaration `builder=AstBuilder()` in the parse method).

Maybe it should not be that way. A quick check revealed that the Ruby version has the same behaviour (using the same `AstBuilder` instance in multiple calls to `parse` does not produce what intuitively can be expected).

**Comment by aslakhellesoy** [comment]
Sounds like all the AstBuilders are buggy then?

**Comment by brasmusson** [comment]
I just checked Python and Ruby. It is possible that these AstBuilders will contain all features parsed, but then `get_result` will always return the first feature parsed (instead of the last).
