### ISSUE TITLE
parsing cucumber JSON/XML reports -> html

### ISSUE THREAD

**Issue by jedi4ever** [cucumber/gherkin3#66]
I'm looking to reuse some logic to convert a json or xml report to html.
I found mostly tools that generate them during the run, but not after the run.

Intended use is to use it together with AWS Devicefarm to generate pretty html.
https://github.com/jedi4ever/devicefarm-cli

Sorry if this is not the right place but you might have some pointers.

**Comment by aslakhellesoy** [comment]
Hi @jedi4ever 

This is a bug tracker, so one of the [support forums](https://cucumber.io/support) are more appropriate to discuss this.
