### ISSUE TITLE
Python package fails to install from PyPI (gherkin-languages.json)

### ISSUE THREAD

**Issue by koterpillar** [cucumber/gherkin3#68]
The version uploaded to PyPI still can't find `gherkin-languages.json`. Can anyone please upload the fix in #63 to PyPI?

**Comment by aslakhellesoy** [comment]
Please don't double-report issues. #63 is fixed, we just haven't made a new release.

**Comment by aslakhellesoy** [comment]
@korerpillar can you try 3.1.0?

**Comment by koterpillar** [comment]
That works, thank you!
