### ISSUE TITLE
Gherkin javascript  astBuilder.reset() Cannot read property 'reset' of undefined

### ISSUE THREAD

**Issue by thetutlage** [cucumber/gherkin3#69]
Trying to use the javascript binding and it says `reset is not a function on astBuilder()`

## Here is the code

```javascript
var Gherkin = require('gherkin');
var parser = new Gherkin.Parser();
var fs = require("fs");

fs.readFile('./ls.feature',function(err,contents){
  var gherkinDoc = contents.toString();
  var feature = parser.parse(gherkinDoc);
  console.log(feature);
});

```

**Comment by aslakhellesoy** [comment]
What version? Got a stack trace?

**Comment by brasmusson** [comment]
To me it looks like that "default arguments" are not implemented in the Javascript version (neither in v3.0.0 nor in v3.1.0), so the code should look like this in v3.1.0 ("reset is not a function on astBuilder()" shows that v3.1.0 was used here):
```
var Gherkin = require('gherkin');
var parser = new Gherkin.Parser(new Gherkin.AstBuilder());
var fs = require("fs");

fs.readFile('./ls.feature',function(err,contents){
  var scanner = new Gherkin.TokenScanner(contents.toString());
  var feature = parser.parse(scanner, new Gherkin.TokenMatcher());
  console.log(feature);
});
```

**Comment by thetutlage** [comment]
Version `3.1.0`

## Stack trace

```javascript
/Users/virk/workspace/labs/gherkinDocs/node_modules/gherkin/lib/gherkin/parser.js:50
    astBuilder.reset();
              ^

TypeError: Cannot read property 'reset' of undefined
    at Parser.parse (/Users/virk/workspace/labs/gherkinDocs/node_modules/gherkin/lib/gherkin/parser.js:50:15)
    at /Users/virk/workspace/labs/gherkinDocs/index.js:10:24
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
```

**Comment by thetutlage** [comment]
@brasmusson It works

**Comment by aslakhellesoy** [comment]
I'm working on a fix for this

**Comment by thetutlage** [comment]
Ohh , i thought this is how it should be used , so i created a pull request with updated docs

**Comment by LukeAskew** [comment]
+1 Can you publish a new release to npm?

**Comment by aslakhellesoy** [comment]
Cutting a release is a little laborious (6 different languages), so if you can live with specifying arguments (and not rely on default ones) that would be great. I'd prefer to defer a new release until we have something more significant to release.
