### ISSUE TITLE
Use “keep a changelog” format

### ISSUE THREAD

**Issue by Zearin** [cucumber/gherkin3#75]
There is an effort to move toward a consistent format for `CHANGELOG.md` files.  AFAIK, it’s not yet very widespread. But it’s simple to understand (and follow), and its principles are based in common sense.  They are outlined here:

http://keepachangelog.com

If you like what you read there, I’d be happy to update `CHANGELOG.md` and send a Pull Request.  

What do you say? :)

**Comment by aslakhellesoy** [comment]
I love changelogs, and I think a consistent format is a good thing, since many developers don't keep them (the same ones who don't tag their releases).

Pleas send us a PR!

**Comment by Zearin** [comment]
@aslakhellesoy Awesome!  I’m on it.  BTW, does your project follow Semantic Versioning?  (It will be mentioned at the top of the change log.)

**Comment by aslakhellesoy** [comment]
> .. does your project follow Semantic Versioning?

Yes it does
