### ISSUE TITLE
Add all implementations to items in `TODO.md`

### ISSUE THREAD

**Issue by Zearin** [cucumber/gherkin3#77]
I’m interested in this project for its Python implementation, so I noticed Python was missing from most of the top-level items in `TODO.md`.  

After a moment, I realized that there seem to be 6 implementations in this project, but many items in `TODO.md` have only 4 items (C#, Java, JavaScript, and Ruby).  

Shouldn’t most of these tasks have all 6 implementations listed?  

(…Or, am I missing something?)

**Comment by aslakhellesoy** [comment]
The TODO was created while there was only 4 implementations. It's obsolete so I just yanked it (and added #78).
