### ISSUE TITLE
Allowed to contribute to ace editor?

### ISSUE THREAD

**Issue by chmontgomery** [cucumber/gherkin3#8]
I just created a [PR against the ace editor to add this repo's js parsing logic](https://github.com/ajaxorg/ace/pull/2429). Ace requires me to sign a license agreement as part of their [contributor requirements](https://github.com/ajaxorg/ace/blob/master/CONTRIBUTING.md#contributing) in order to do this. Part of the legalese states: "In brief, by submitting your code to Cloud9, you are granting us a right to use that code under the terms of this Agreement, including providing it to others. You are also certifying that you wrote it, and that you are allowed to license it to us. You are not giving up your copyright in your work."

I wanted to make sure you're ok with me doing this. Since gherkin3 is under MIT I figured it was fine, however I wanted to make sure.

**Comment by aslakhellesoy** [comment]
Thanks for asking @chmontgomery 

You are currently in breach of Gherkin3's MIT license because you have copied the Gherkin3 code without including the license. More explicitly [this](https://github.com/cucumber/gherkin3/blob/master/LICENSE#L12-L13).

You did not write the Gherkin3 code that you have copied into your Ace fork, and that you are planning to submit to Cloud9.

In other words, you are not in compliance with Cloud9's contributor requirements. See point 5 and 7 in [The Individual CLA](https://docs.google.com/forms/d/1MfmfrxqD_PNlNsuK0lC2KSelRLxGLGfh_wEcG0ijVvo/viewform). (I assume you are an individual and not acting on behalf of a company).

**Comment by aslakhellesoy** [comment]
I'm sure we'll find a way around this, and I really appreciate the effort you're putting into making Gherkin3 work with Ace!

From what I can tell you'll be in compliance with both Gherkin3's MIT license and Cloud9's requirements if you include the MIT license in the AMD build.

I'm certainly fine with Gherkin3 being included in Ace as long as our license is preserved.

**Comment by chmontgomery** [comment]
sounds good. I'll update the src to include the license. As part of ace's build process, however, the licenses are stripped from the minified src. I assume this is ok? It just needs to be part of the src files?

**Comment by aslakhellesoy** [comment]
It doesn't matter what shape or form the source code is in. The license must follow the source code, also ehen minified. Just read the license. It's not complicated.

**Comment by chmontgomery** [comment]
I have read the license. What I'm saying is: my hands are tied with ace's build system. I can easily put your license in [the src files](https://github.com/ajaxorg/ace/tree/master/lib/ace) but when ace's build runs it removes all comments from src files, including your license, and deposits the results here: https://github.com/ajaxorg/ace-builds. This is an effect of https://github.com/mozilla/dryice.

The only work-around I could think of is modifying ace's [`Makefile.dryince.js`](https://github.com/ajaxorg/ace/blob/master/Makefile.dryice.js) to copy over gherkin's license as a separate file that can sit along side the generated files. If you're not happy with that approach then I'm open to other suggestions.

**Comment by aslakhellesoy** [comment]
I'm afraid this is something you need to resolve with the Ace project. It's in their own interest that their build system is aligned with their contributor requirements and the licenses of 3rd party code that they include in their builds.

I'm not sure a change to the Dryice is required, it would suffice to send a PR to the ace-build project where you add a `LICENSE.gherkin` file, which is a copy of ours, with the following text as the first line:

```
This license pertains to the files in the mode-gherkin.js, xxx.js files. 
```

Or something similar. I'm sure the Ace folks would be happy to help.

I will make sure our license is embedded into all `dist/*.js` files.

**Comment by aslakhellesoy** [comment]
@chmontgomery I just pushed 55d2419938f1aad5402753d145c8df6d7193266a.

When you run `make` this should create a `javascript/dist/gherkin.js` file with everything bundled in one file, and the MIT license as a header.

If Ace's build system removes the license during build, just send Ace a PR to add the license manually at the root directory as I described in my previous comment.

**Comment by chmontgomery** [comment]
I should be able to modify their build file relatively easily to generate a stand-alone license that lives alongside the file. I'll try that

**Comment by chmontgomery** [comment]
I've updated my PR against ace to properly copy `LICENSE.gherkin` to each output folder during build time so that the license follows the code. Hopefully this suffices?

**Comment by aslakhellesoy** [comment]
I guess we can close this now since it doesn't look like the Gherkin3 code will end up in the Ace repo.
