### ISSUE TITLE
Readme and Ruby require

### ISSUE THREAD

**Issue by vincent-psarga** [cucumber/gherkin3#92]
I just noticed a small issue in the Readme.md and documentation.
When trying to use the gem as specified in the example:

    # Ruby
    require 'gherkin3'

I get an error "`require': cannot load such file -- gherkin3 (LoadError)". Replacing it by:

    require 'gherkin3/parser'

works like a charm. I prefer not to make a pull request, I ain't sure this comes from our project configuration or a real issue in the documentation.

Cheers.

**Comment by aslakhellesoy** [comment]
Thanks for the heads up!
