### ISSUE TITLE
Nest comments under parents e.g. feature.comments, step.comments

### ISSUE THREAD

**Issue by jimCresswell** [cucumber/gherkin3#96]
Hi,

I'm in the process of migrating to the Gherkin 3 JavaScript implementation and dropping my custom Gherkin 2 Visitor. It's really great, thanks. I have noticed that comments are grouped together in a single array, I'd previously implemented them as belonging to a feature, step, example etc.

Would it be possible to have comments belonging to their parents objects so we would end up with feature.comments, background.comments, scenarioDefinition.comments etc? I imagine it might be possible that the logic could be similar to the way tags are attached to features and scenarios.

Thanks,
Jim

**Comment by brasmusson** [comment]
The comment are intentionally placed in the Feature node in the ast, see #24 and https://groups.google.com/forum/#!msg/cukes-devs/RCnkmXsLQEs/Nj3AtFJ1qAoJ. One reason to do so is to allow comment to be anywhere in the feature file.

**Comment by jimCresswell** [comment]
Okay, thanks. I'll work around it using line numbers.
